name: Build Linux App

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install Qt dependencies
        run: |
          sudo apt update
          sudo apt install -y libxcb-cursor0

      - name: Build app
        run: |
          pyinstaller main.py --noconsole --onefile --icon=icons/icon_2048x.ico --add-data "sounds:sounds" --add-data "icons:icons" --add-data "datas:datas" --add-data "images:images" --add-data "run:run"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist/