name: Build Mac App

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build app
        run: |
          pyinstaller autorun.py --noconsole --onefile --collect-all PyQt6
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist/